# Generated by Django 5.0.2 on 2024-02-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_breakdown_exam_question_exammodule_exam_modules'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='Career',
            new_name='career',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='question',
            new_name='questions',
        ),
        migrations.AlterField(
            model_name='breakdown',
            name='answer',
            field=models.CharField(default='-', max_length=5),
        ),
        migrations.AlterField(
            model_name='breakdown',
            name='correct',
            field=models.CharField(default='-', max_length=5),
        ),
    ]
