# Generated by Django 5.0.2 on 2024-02-21 21:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Imagen de la pregunta'),
        ),
    ]
